---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

Mutual Exclusivity Downsampling Demo

```{r}
#Run function with this: trasformabilitychecker(12,100,'BRAF','NRAS','ATI','N','V600E','Q61L') 
#meds mutual exclusivity ds
# trasformabilitychecker<- function(nsubsamples,nsims,nameposctrl1,nameposctrl2,namegene,mtn,nameposctrl1mt,nameposctrl2mt){
#Version 10    4/26/18
#Data can be either in the form of strings (mutation vs NaN) or as numerics (1 vs 0). Logicals (TRUE/FALSE) can be added as well
# rm(list=ls())
require(ggplot2) #is it ok to use this line at the start of the script?
require(dplyr)
# library(ggplot2,lib.loc="~/Ati") #this wasn't working so I'm jjust using library(ggplot2)
library(ggplot2)
library(dplyr)
# ##################################Hardcoded Parts#############################################################################
  nsubsamples=12 # maybe this can be removed because.
  nsims<-100 #
  #Positive control 1
  nameposctrl1<-'BRAF'
  #Positive control 1
  nameposctrl2<-'NRAS'
  #Oncogene in Question
  namegene<-'ATI'
  #Mutation Boolean (Y or N)
  mtn<-'N'
  #Name Mutation for Positive Ctrl 1
  nameposctrl1mt<-'V600E'
  #Name of Mutation for Positive Ctrl 2
  nameposctrl2mt<-'Q61L'

##################################Data Sorting#############################################################################
alldata=read.csv("data/All_Data_V2.csv",sep=",",header=T,stringsAsFactors=F)

#Sorting by whether user wants to search by specific mutations or the general format overall
if(mtn=='N') {
  Positive_Ctrl1=as.numeric(!grepl("NaN",do.call("$",list(alldata,nameposctrl1)),ignore.case = TRUE))
  Positive_Ctrl2=as.numeric(!grepl("NaN",do.call("$",list(alldata,nameposctrl2)),ignore.case = TRUE))
} else {
  Positive_Ctrl1=as.numeric(grepl(nameposctrl1mt,do.call("$",list(alldata,nameposctrl1)),ignore.case = TRUE))
  Positive_Ctrl2=as.numeric(grepl(nameposctrl2mt,do.call("$",list(alldata,nameposctrl2)),ignore.case = TRUE))
}
genex=as.numeric(!grepl(paste(c("NaN","0"), collapse = "|"),do.call("$",list(alldata,namegene)))) #Searching for 'NaN' or '0' in desired gene. A positive hit returns 0 and vise versa.

alldata_comp=cbind(alldata[,c(1,2)],Positive_Ctrl1,Positive_Ctrl2,genex) #Data frame with all the data compiled. I add in random array to this later

genex_replication_prop=sum(genex)/length(genex) #Calculating Replication Proportion

#Creating Random Array (Negative Control)
rndmarray=rbinom(length(Positive_Ctrl1),1,genex_replication_prop) #change alldata            #Decided to just call random array in the for-loop
alldata_comp=cbind(alldata_comp,rndmarray) #Adding in random array to compiled gene data

all_genex     =alldata_comp[alldata_comp$genex!=0,] #These will be used later for sampling
all_not_genex =alldata_comp[alldata_comp$genex==0,]
all_pc1       =alldata_comp[alldata_comp$Positive_Ctrl1!=0,]
all_not_pc1   =alldata_comp[alldata_comp$Positive_Ctrl1==0,]
all_pc2       =alldata_comp[alldata_comp$Positive_Ctrl2!=0,]
all_not_pc2   =alldata_comp[alldata_comp$Positive_Ctrl2==0,]
all_rndm      =alldata_comp[alldata_comp$rndmarray!=0,]
all_not_rndm  =alldata_comp[alldata_comp$rndmarray==0,]

#max subsample size is whichever integer is the minimum of: number of genex in sample vs. number of NOTgenex or PC1 or PC2 in sample*genexreplication proportion. For example we had 165 PC1s, therefore 340-175=165 PC1s in our data. Since we want to sample 7.35% positive hits and 92.65% negative hits, a sample containing too many positive hits can impose an upper bound on our subsampling size.
maxsubsamplesize=min(c(genex_replication_prop*length(alldata_comp$Positive_Ctrl1),floor((length(alldata_comp$Positive_Ctrl1)-sum(alldata_comp$Positive_Ctrl1))*genex_replication_prop),floor((length(alldata_comp$Positive_Ctrl1)-sum(alldata_comp$Positive_Ctrl2))*genex_replication_prop),floor((length(alldata_comp$Positive_Ctrl1)-sum(alldata_comp$genex))*genex_replication_prop)))
##################################Errors#############################################################################
#Part in the code where exceeding the max limit, i.e. 25, returns an error
if(nsubsamples>maxsubsamplesize){
  stop("Desired Subsample Size Exceeds Maxium Subsample Size")
}
#Returns error if max value > 1. Will this ever be a problem?
if(max(alldata_comp$Positive_Ctrl1|alldata_comp$Positive_Ctrl2|alldata_comp$genex)>1){
  stop("Data Contains Integers >1. Please use either logicals or characters")
}
print(paste("Current proportion of GeneX =",round(genex_replication_prop*100,3),"%"))#print to console
print(paste("Total Number of Samples =",length(alldata_comp[,1])))
print(paste("Number of Positive Control 1 Hits =",sum(alldata_comp$Positive_Ctrl1)))
print(paste("Number of Positive Control 2 Hits =",sum(alldata_comp$Positive_Ctrl2)))
print(paste("Number of Gene of Interest Hits =",sum(alldata_comp$genex)))
print(paste("The maximum allowed subsample size is",maxsubsamplesize))
print(paste("Therefore, during simulations, Positive Control 1 will be downsampled from",sum(alldata_comp$Positive_Ctrl1),"to",maxsubsamplesize,", and Positive Control 2 will be downsampled from",sum(alldata_comp$Positive_Ctrl2),"to",maxsubsamplesize))


##################################Contingency Table Function#############################################################################

contab_maker<- function(gene1,gene2,arrayname) {
  gene1_gene2_nn=nrow(arrayname[gene1==0 & gene2==0,]) #N N
  gene1_gene2_ny=nrow(arrayname[gene1==0 & gene2!=0,]) #N Y
  gene1_gene2_yn=nrow(arrayname[gene1!=0 & gene2==0,]) #Y N
  gene1_gene2_yy=nrow(arrayname[gene1!=0 & gene2!=0,]) #Y Y
  
  con_tab_gene1_gene2=rbind(c(gene1_gene2_nn,gene1_gene2_ny),c(gene1_gene2_yn,gene1_gene2_yy))
  con_tab_gene1_gene2
}

#Contingency Tables:
con_tab_pctrl1_genex=contab_maker(alldata_comp$Positive_Ctrl1,alldata_comp$genex,alldata_comp)
con_tab_pctrl2_genex=contab_maker(alldata_comp$Positive_Ctrl2,alldata_comp$genex,alldata_comp)
con_tab_pctrl1_pctrl2=contab_maker(alldata_comp$Positive_Ctrl1,alldata_comp$Positive_Ctrl2,alldata_comp)
con_tab_pctrl1_rndmarray=contab_maker(alldata_comp$Positive_Ctrl1,alldata_comp$rndmarray,alldata_comp)
con_tab_pctrl2_rndmarray=contab_maker(alldata_comp$Positive_Ctrl2,alldata_comp$rndmarray,alldata_comp)

#Fisher's Exact Test
p_p1_genex=fisher.test(con_tab_pctrl1_genex)
p_p2_genex=fisher.test(con_tab_pctrl2_genex)
p_p1_p2=fisher.test(con_tab_pctrl1_pctrl2)
p_p1_rndm=fisher.test(con_tab_pctrl1_rndmarray)
p_p2_rndm=fisher.test(con_tab_pctrl2_rndmarray)

##################################Simulations###################################################################################
# 3 Loops here. For Sumsample size, Simulation Number, and Experiment Number.
# Experiment number: There are 6 experiments refers to combinations of fisher's test for 4 samples (4C2=6)

#Need to modify so that nsubsamples can be a range (like 10:100) rather than a number (like 100)
nexperiments=6 #to make nexperiments a variable, alldatasamplepvals will need to be defined differently
simresults<-matrix(nrow=nsims*nsubsamples*nexperiments,ncol=9)

ct=1


for (subsamplenumber in 1:nsubsamples){
  simresults[c(ct:((ct+(nsims*nexperiments))-1)),2]=subsamplenumber #Subsample Number: This updates the next n rows with the subsample number that the loop is on. n is calculated by number of experiments * number of simulations
  subsamplenumbernegativehits=round(subsamplenumber/(genex_replication_prop))-subsamplenumber #This determines the number of non-hits for the sample 
  for (simnumber in 1:nsims){
      alldata_comp$rndmarray=rbinom(length(Positive_Ctrl1),1,genex_replication_prop) #Creates random array. Note: we're updating random array at each simulation within each subsample size.
    
      simresults[c(ct:((ct+nexperiments)-1)),3]=simnumber #Simulation Number. This updates the next 6 rows with the simulation number that the loop is on.
        
      sample_genex     =all_genex[sample(length(all_genex$genex),subsamplenumber,replace=F,prob=NULL),]
      sample_not_genex =all_not_genex[sample(length(all_not_genex$genex),subsamplenumbernegativehits,replace=F,prob=NULL),]
      sample_pc1       =all_pc1[sample(length(all_pc1$Positive_Ctrl1),subsamplenumber,replace=F,prob=NULL),]
      sample_not_pc1   =all_not_pc1[sample(length(all_not_pc1$Positive_Ctrl1),subsamplenumbernegativehits,replace=F,prob=NULL),]
      sample_pc2       =all_pc2[sample(length(all_pc2$Positive_Ctrl2),subsamplenumber,replace=F,prob=NULL),]
      sample_not_pc2   =all_not_pc2[sample(length(all_not_pc2$Positive_Ctrl2),subsamplenumbernegativehits,replace=F,prob=NULL),]
      sample_rndm      =all_rndm[sample(length(all_rndm$rndmarray),subsamplenumber,replace=F,prob=NULL),]
      sample_not_rndm  =all_not_rndm[sample(length(all_not_rndm$rndmarray),subsamplenumbernegativehits,replace=F,prob=NULL),]
      
      #Combining n (subsample number) hits and m (subsamplenegativenumber) non-hits
      sample_genex_comb =rbind(sample_genex,sample_not_genex) #Dunno if this is the right way to do it
      sample_pc1_comb   =rbind(sample_pc1,sample_not_pc1)
      sample_pc2_comb   =rbind(sample_pc2,sample_not_pc2)
      sample_rndm_comb  =rbind(sample_rndm,sample_not_rndm)
      
      alldata_comp_sample<-as.data.frame(cbind(sample_pc1_comb,sample_pc2_comb,sample_genex_comb,sample_rndm_comb))  #Creating array with samples so that contab_maker can use them
      
      #contingency tables
      con_tab_sample_pctrl1_genex=contab_maker(sample_pc1_comb$Positive_Ctrl1,sample_pc1_comb$genex,sample_pc1_comb) #Double check to see if this is the right way to do it
      con_tab_sample_pctrl2_genex=contab_maker(sample_pc2_comb$Positive_Ctrl2,sample_pc2_comb$genex,sample_pc2_comb)
      con_tab_sample_pctrl1_pctrl2=contab_maker(sample_pc1_comb$Positive_Ctrl1,sample_pc1_comb$Positive_Ctrl2,sample_pc1_comb) #note how sampling pc1 vs pc2 and then finding pc2 vs pc1 has drastically different p-values. Add code that looks at which of the samples has a smaller size and then chooses to sample for 7% of that first
      con_tab_sample_pctrl1_pctrl2=contab_maker(sample_pc2_comb$Positive_Ctrl2,sample_pc2_comb$Positive_Ctrl1,sample_pc2_comb)
      con_tab_sample_pctrl1_rndmarray=contab_maker(sample_pc1_comb$Positive_Ctrl1,sample_pc1_comb$rndmarray,sample_pc1_comb)
      con_tab_sample_pctrl2_rndmarray=contab_maker(sample_pc2_comb$Positive_Ctrl2,sample_pc2_comb$rndmarray,sample_pc2_comb)
      con_tab_sample_genex_rndmarray=contab_maker(sample_genex_comb$genex,sample_genex_comb$rndmarray,sample_genex_comb)
      
      #Fishers exact test
      p_s_p1_genex=fisher.test(con_tab_sample_pctrl1_genex,conf.int = 50) #p_s_ stands p-value, sample. Can name these better in the future
      p_s_p2_genex=fisher.test(con_tab_sample_pctrl2_genex,conf.int = 50) #Could check if pc1_genex and genex_pc1 give the same p-value just to verify our test
      p_s_p1_p2=fisher.test(con_tab_sample_pctrl1_pctrl2,conf.int = 50)
      p_s_p1_rndm=fisher.test(con_tab_sample_pctrl1_rndmarray,conf.int = 50)
      p_s_p2_rndm=fisher.test(con_tab_sample_pctrl2_rndmarray,conf.int = 50)
      p_s_genex_rndm=fisher.test(con_tab_sample_genex_rndmarray,conf.int = 50)
    
      #Creating df that has all the simulation data so far. This will be used by the simresults df later.
      alldatasamplepvals<-as.data.frame(cbind(p_s_p1_genex$p.value,p_s_p2_genex$p.value,p_s_p1_p2$p.value,p_s_p1_rndm$p.value,p_s_p2_rndm$p.value,p_s_genex_rndm$p.value))
      colnames(alldatasamplepvals)=c("p_s_p1_genex","p_s_p2_genex","p_s_p1_p2","p_s_p1_rndm","p_s_p2_rndm","p_s_genex_rndm")
      alldatasampleORvals<-as.data.frame(cbind(p_s_p1_genex$estimate,p_s_p2_genex$estimate,p_s_p1_p2$estimate,p_s_p1_rndm$estimate,p_s_p2_rndm$estimate,p_s_genex_rndm$estimate))
      colnames(alldatasampleORvals)=c("p_s_p1_genex","p_s_p2_genex","p_s_p1_p2","p_s_p1_rndm","p_s_p2_rndm","p_s_genex_rndm")
      alldatasampleCIub<-as.data.frame(cbind(p_s_p1_genex$conf.int[2],p_s_p2_genex$conf.int[2],p_s_p1_p2$conf.int[2],p_s_p1_rndm$conf.int[2],p_s_p2_rndm$conf.int[2],p_s_genex_rndm$conf.int[2]))
      colnames(alldatasampleCIub)=c("p_s_p1_genex","p_s_p2_genex","p_s_p1_p2","p_s_p1_rndm","p_s_p2_rndm","p_s_genex_rndm")
      alldatasampleCIlb<-as.data.frame(cbind(p_s_p1_genex$conf.int[1],p_s_p2_genex$conf.int[1],p_s_p1_p2$conf.int[1],p_s_p1_rndm$conf.int[1],p_s_p2_rndm$conf.int[1],p_s_genex_rndm$conf.int[1]))
      colnames(alldatasampleCIlb)=c("p_s_p1_genex","p_s_p2_genex","p_s_p1_p2","p_s_p1_rndm","p_s_p2_rndm","p_s_genex_rndm")
    
    for (expnumber in 1:nexperiments) {
      simresults[ct,1]=ct #Total Count
      simresults[ct,4]=expnumber #Experiment Number
      simresults[ct,5]=colnames(alldatasamplepvals[expnumber]) #Experiment Name
      simresults[ct,6]=alldatasamplepvals[1,expnumber] #Experiment P-value. Trying to convert it into numerics
      simresults[ct,7]=as.numeric(alldatasampleORvals[1,expnumber]) #Experiment OR-value
      simresults[ct,8]=as.numeric(alldatasampleCIub[1,expnumber]) #Experiment 95% Upper Confidence Interval. Can be changed to other CI
      simresults[ct,9]=as.numeric(alldatasampleCIlb[1,expnumber]) #Experiment 95% Lower Confidence Interval. Can be changed to other CI
      
      ct=ct+1
    }
  }
}
colnames(simresults)=c("totCt","subsample_size","sim_num","exp_num","exp_name","p_val","OR_val","CIub","CIlb")
simresults=as.data.frame(simresults, stringsAsFactors = F, )
simresults=transform(simresults,p_val=as.character(p_val))
simresults=transform(simresults,p_val=as.numeric(p_val))

simresults=transform(simresults,exp_num=as.character(exp_num))
simresults=transform(simresults,exp_num=as.numeric(exp_num))

simresults=transform(simresults,sim_num=as.character(sim_num))
simresults=transform(simresults,sim_num=as.numeric(sim_num))

simresults=transform(simresults,subsample_size=as.character(subsample_size))
simresults=transform(simresults,subsample_size=as.numeric(subsample_size))

simresults=transform(simresults,OR_val=as.character(OR_val))
simresults=transform(simresults,OR_val=as.numeric(OR_val))

simresults=transform(simresults,CIub=as.character(CIub))
simresults=transform(simresults,CIub=as.numeric(CIub))

simresults=transform(simresults,CIlb=as.character(CIlb))
simresults=transform(simresults,CIlb=as.numeric(CIlb))

##################################Plotting#############################################################################
#Using ggplot
########Plotting P-values
datapoints=simresults %>% 
  group_by(subsample_size,exp_name) %>%
  summarise(avg_p_val=mean(p_val))
#6 Different plots divided by Facet Wrap. Add error bars to all of these
pvalplot<-ggplot(datapoints,aes(x=subsample_size,y=avg_p_val))+geom_point()+geom_smooth(se=FALSE,aes(size=.01))+facet_wrap(~exp_name)+ggtitle("P-value across 100 simulations")+xlab("Subsample Size")+ylab("Mean p-value")+theme_bw()+theme(plot.title = element_text(hjust=.5))
#One Plot with all the scatters
pvalplot2<-ggplot(datapoints,aes(x=subsample_size,y=avg_p_val,color=exp_name))+geom_point()+geom_smooth(se=FALSE,size=1.5)+ggtitle("P-value across 100 simulations")+xlab("Subsample Size")+ylab("Mean p-value")+theme_bw()+theme(plot.title = element_text(hjust=.5))

#P values vs Sim Number at subsample size of 10 
datapointssims=simresults %>% 
  filter(subsample_size==10) %>%
  group_by(sim_num,exp_name) %>%
  summarise(avg_p_val=mean(p_val))
pvalplot3<-ggplot(datapointssims,aes(x=sim_num,y=avg_p_val))+geom_point()+geom_smooth()+facet_wrap(~exp_name)+ggtitle("P value across Simulations. Subsample Size = 10")+xlab("Simulation Number")+ylab("P-value")+theme_bw()+theme(plot.title = element_text(hjust=.5))

#P values vs Sim Number at subsample size of 3 
datapointssims=simresults %>% 
  filter(subsample_size==3) %>%
  group_by(sim_num,exp_name) %>%
  summarise(avg_p_val=mean(p_val))
pvalplot4<-ggplot(datapointssims,aes(x=sim_num,y=avg_p_val))+geom_point()+geom_smooth()+facet_wrap(~exp_name)+ggtitle("p-val of 100 simulations @ Subsample Size 10")+xlab("Simulation Number")+ylab("P-value")+theme_bw()+theme(plot.title = element_text(hjust=.5))

#####Plotting OR Values
datapointsOR=simresults %>%
  group_by(subsample_size,exp_name) %>%
  summarise(avg_OR=mean(OR_val),avg_CIub=mean(CIub),avg_CIlb=mean(CIlb))

orvalplot1<-ggplot(datapointsOR,aes(x=subsample_size,y=avg_OR))+geom_point()+geom_smooth(se=FALSE)+facet_wrap(~exp_name)+ggtitle("Odds Ratio across 100 Simulations")+xlab("Subsample Size")+ylab("Mean OR-value")+theme_bw()+theme(plot.title = element_text(hjust=.5))
ggsave("ORvalplot3a.pdf")
orvalplot2a<-ggplot(datapointsOR,aes(x=subsample_size,y=avg_OR,color=exp_name))+geom_point()+geom_smooth(se=FALSE)+ggtitle("Odds Ratio across 100 Simulations")+xlab("Subsample Size")+ylab("Mean OR-value")+theme_bw()+theme(plot.title = element_text(hjust=.5))
#OR Vals with CIs, non log transformed combined
orvalplot2b<-ggplot(datapointsOR,aes(x=subsample_size,y=avg_OR,color=exp_name))+geom_point()+geom_smooth(se=FALSE)+geom_ribbon(aes(ymin=avg_CIub,ymax=avg_CIlb),alpha=.2)+ggtitle("Mean OR-val of 100 simulations ~ Subsample Size")+xlab("Subsample Size")+ylab("Mean OR-value")+theme_bw()+theme(plot.title = element_text(hjust=.5))
#OR Vals with CIs, nonlog transformed, uncomined
orvalplot3a<-ggplot(datapointsOR,aes(x=subsample_size,y=avg_OR))+geom_point()+geom_smooth(se=FALSE)+geom_ribbon(aes(ymin=avg_CIub,ymax=avg_CIlb),alpha=.2)+facet_wrap(~exp_name)+ggtitle("Mean OR-val of 100 simulations ~ Subsample Size")+xlab("Subsample Size")+ylab("Mean OR-value")+theme_bw()+theme(plot.title = element_text(hjust=.5))
#log transformed, with CIs
orvalplot3b<-ggplot(datapointsOR,aes(x=subsample_size,y=log(avg_OR)))+geom_point()+geom_smooth(se=FALSE)+geom_ribbon(aes(ymin=log(avg_CIub),ymax=log(avg_CIlb)),alpha=.2)+facet_wrap(~exp_name)+ggtitle("Mean OR-val of 100 simulations ~ Subsample Size")+xlab("Subsample Size")+ylab("Log(Mean OR-value)")+theme_bw()+theme(plot.title = element_text(hjust=.5))
orvalplot4<-ggplot(datapointsOR,aes(x=subsample_size,y=log(avg_OR),color=exp_name))+geom_point()+geom_smooth(se=FALSE)+geom_ribbon(aes(ymin=log(avg_CIub),ymax=log(avg_CIlb)),alpha=.2)+ggtitle("Mean OR-val of 100 simulations ~ Subsample Size")+xlab("Subsample Size")+ylab("Log(Mean OR-value)")+theme_bw()+theme(plot.title = element_text(hjust=.5))

########################Kolmogorov Smirnov Probability Distribution Test########################
#Making KS Test DF
ct=1
expcombinations=(factorial(nexperiments)/(factorial(2)*factorial(nexperiments-2)))
exppermutations=(factorial(nexperiments)/(factorial(nexperiments-2)))
ksresults<-matrix(nrow=nsubsamples*exppermutations,ncol=8)
for (subsamplenumber in 1:nsubsamples){
datapointsks=simresults %>%
  filter(subsample_size==subsamplenumber) %>%
  group_by(exp_num,sim_num)
  ksresults[c(ct:((ct+exppermutations)-1)),2]=subsamplenumber
  for (expnumber in 1:nexperiments){
    for (secondexpnumber in 1:nexperiments){
      if(secondexpnumber!=expnumber){ #To Avoid comparing Exp1 to Exp1 etc
    kstestresults=ks.test(datapointsks$OR_val[datapointsks$exp_num==expnumber],datapointsks$OR_val[datapointsks$exp_num==secondexpnumber])
      ksresults[ct,1]=ct #Total Count
      ksresults[ct,3]=expnumber #Experiment Number
      ksresults[ct,4]=datapointsks$exp_name[expnumber] #Experiment Name
      ksresults[ct,5]=secondexpnumber #Experiment Number
      ksresults[ct,6]=datapointsks$exp_name[secondexpnumber] #Experiment Name
      ksresults[ct,7]=kstestresults$p.value #Experiment P-value. Trying to convert it into numerics
      ksresults[ct,8]=kstestresults$statistic #Experiment OR-value
      ct=ct+1
      }
    }
  }
}
#Managing Ksresults dataframe
colnames(ksresults)=c("totCt","subsample_size","exp_num1","exp_name1","exp_num2","exp_name2","p_val","d_val")
ksresults=as.data.frame(ksresults, stringsAsFactors = F, )
ksresults=transform(ksresults,subample_size=as.character(subsample_size),exp_num1=as.character(exp_num1),exp_num2=as.character(exp_num2),p_val=as.character(p_val),d_val=as.character(d_val))
ksresults=transform(ksresults,subsample_size=as.numeric(subsample_size),exp_num1=as.numeric(exp_num1),exp_num2=as.numeric(exp_num2),p_val=as.numeric(p_val),d_val=as.numeric(d_val))

#Data Sorting
datapoints_ks_pval=ksresults %>%
  filter(exp_num2==4)
#Plotting  
  ksvalplot<-ggplot(datapoints_ks_pval,aes(x=subsample_size,p_val,color=exp_name1))+geom_point()+geom_smooth(se=FALSE,size=1.5)+ggtitle("P-value from KS Test across 100 simulations")+xlab("Subsample Size")+ylab("P-value")+theme_bw()+theme(plot.title = element_text(hjust=.5))

```
```{r}
orvalplot1
orvalplot2a
orvalplot2b
orvalplot3a
orvalplot3b
orvalplot4
ksvalplot
```
